### ISSUE TITLE
Gráfico ejecuta Pymol

### ISSUE THREAD

**Issue by JoaquinDecima** [BioinformaticaUNQ/calcio_binding_regions_visualazer-grupo1#1]
No es urgente, pero cero que podríamos ver otra forma de ejecutar el gráfico sin que ejecute todo el pymol, en caso de ser así deberiamos agregar como dependencia pymol y en ves de "mostrar Grafico" la opcion que ofreceriaos seria "Ejecutar en Pymol"

**Comment by SabaPablo** [comment]
Resuelto!
